# This file was generated by GoReleaser. DO NOT EDIT.
cask "brig" do
  name "brig"
  desc "the lightweight, native Go CLI for devcontainers"
  homepage ""
  version "0.0.6-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brig"

  on_macos do
    on_intel do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_darwin_amd64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "9e1cffa0afb594c77f6b6e43e5f8a4da2554ab9ecc5bec203cb3b932157d84e2"
    end
    on_arm do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_darwin_arm64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "61bf831d0c804d57ca610247ca20b582cb615c6b469a595faa0f5e7e8e250caf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_linux_amd64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "71560b959116b9206a87ff355100c620a1ddb9e1bd8a9c5ee0046e34f2172241"
    end
    on_arm do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_linux_arm64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "85628a84a1135d4d8d8d9fd501e25c1cfc5e5b499499326f5b046d76771d9d1c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xatttr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brig"]
    end
  end

  # No zap stanza required
end
