# This file was generated by GoReleaser. DO NOT EDIT.
cask "brig" do
  name "brig"
  desc "the lightweight, native Go CLI for devcontainers"
  homepage ""
  version "0.0.6-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brig"

  on_macos do
    on_intel do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_darwin_amd64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "b75c90db697412a3fcbd6736bec8a96da7e902ec0f09a0c531769957952ee85f"
    end
    on_arm do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_darwin_arm64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "d3e296d6fdf3a0855fe9f1dbbb07be6beb13196bb895a9e1e52a666800ca434c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_linux_amd64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "5326c3b42d2c68197a31410cd7fa329a145ced95cc6e42afbb0e0a0164e3a093"
    end
    on_arm do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_linux_arm64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "27d17b38b28c02c47ae1356f313839b956469851bdeec55baa8a0af42ffcc5bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xatttr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brig"]
    end
  end

  # No zap stanza required
end
