# This file was generated by GoReleaser. DO NOT EDIT.
cask "brig" do
  name "brig"
  desc "the lightweight, native Go CLI for devcontainers"
  homepage ""
  version "0.0.7-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brig"

  on_macos do
    on_intel do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_darwin_amd64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "fa2b4b62d1a489e9066f10c714f30945a3aa1d1127a105af980d8a49104bd5a8"
    end
    on_arm do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_darwin_arm64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "54351dd9239df1908eb71878dba92072f6cf2f62e13e1c861685bd47b74f15b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_linux_amd64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "dbf1100b32c341dfd885cf17384b21d2cea769dc8295435a717a18b284254827"
    end
    on_arm do
      url "https://github.com/nlsantos/brig/releases/download/v#{version}/brig_#{version}_linux_arm64.tar.xz",
        verified: "github.com/nlsantos/brig"
      sha256 "d370554f1833ad61bfe572c6ab3aea9f8cfeec7bb224c8cc88d2959396cae523"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xatttr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brig"]
    end
  end

  # No zap stanza required
end
